### ISSUE TITLE
Themes not working with new Component Story Format in Storybook 5.2

### ISSUE THREAD

**Issue by vjwilson** [tonai/storybook-addon-themes#10]
The add-on doesn't add classes, unless we use the `.storiesOf` style (https://storybook.js.org/docs/formats/storiesof-api/)

I need to add a theme class to the stories, because my project's colors don't work without one or the other "theme" class on a parent element.

We are just starting with Storybook, so we wanted to use only the new Component Story Format (CSF) in Storybook 5.2. (https://storybook.js.org/docs/formats/component-story-format/)

I have tried it with and without using the decorators.

1. Is this a known issue, and are there any plans to support the new CSF style?
2. Am I just doing something in my setup (quoted below)?

Versions:
* "@storybook/react": "^5.2.1"
* "storybook-addon-themes": "^5.2.0"

This `.storybook/config.js` is not working:
```
import { addDecorator, addParameters, configure } from '@storybook/react';
import { withThemes } from 'storybook-addon-themes';

configure(require.context('../src', true, /\.stories\.js$/), module);

addParameters({
  themes: [
    { name: 'Light Theme', class: 'theme-light', color: '#9199b1', default: true },
    { name: 'Dark Theme', class: 'theme-dark', color: '#5e667d' },
  ],
});

addDecorator(withThemes);  // <-- still doesn't work, whether this is used or not
```

**Comment by tonai** [comment]
Hi @vjwilson and thanks for reporting.
I will check what it means to support CSF.

**Comment by tonai** [comment]
Hi @vjwilson, I have tested the lib using the CSF style and I haven't got any problem.

In your `.storybook/config.js` you have to call the `configure` function at the end.

I will update the doc and include a CSF exemple.

**Comment by vjwilson** [comment]
@tonai Thanks for the clarification. Really like your add-on.

**Comment by tonai** [comment]
My pleasure 🙂.
Thanks for your comment.
