### ISSUE TITLE
Adding class to the HTML element.

### ISSUE THREAD

**Issue by simobari** [tonai/storybook-addon-themes#12]
Hello there,
I'm using storybook with VUE and it would be extremely useful to be able to add the class to HTML element, instead of BODY.

Thanks

**Comment by tonai** [comment]
Hello, yes it is a known issue.
Each framework needs its own decorator, but that means custom code each time.
I will try to have a look but it's currently hard to have some free time.

**Comment by tonai** [comment]
Hi,
I released a new version (5.3.0) with vue support for the decorator usage.
Thanks for reporting.
