### ISSUE TITLE
Add screenshots to the docs

### ISSUE THREAD

**Issue by tskarhed** [tonai/storybook-addon-themes#18]
Hi! I'm currently looking through this addon, and I'm trying to decide how and if I want use it. Some screenshots in the README would be appreciated. 

Is it possible to change between themes that have the Storybook theme format?

Thanks, and awesome work on writing an addon! :smiley_cat:

**Comment by tonai** [comment]
Hi @tskarhed and thanks for your comment.
I will have a look to add some screenshots or maybe a animated gif that shows the switcher in action.

I'm not sure what you are talking about when saying "Storybook theme format" ?
Is it the possibility to change the theme of the storybook manager ? (https://storybook.js.org/docs/configurations/theming/)

**Comment by tskarhed** [comment]
Hi, just wanted to say that I found what I was looking for in this addon https://github.com/hipstersmoothie/storybook-dark-mode

**Comment by tonai** [comment]
Thank you for your message and glad that you find what you were looking for. :)
