### ISSUE TITLE
Prevent "clear theme" if default theme is set

### ISSUE THREAD

**Issue by webholics** [tonai/storybook-addon-themes#26]
I currently have the case that a theme should always be set. If I provide a default theme its weird that the user is still able to clear this theme. In my case if there is no theme there are no styles.
So I would propose that if a default theme is set then a theme should always be set and there should be not "clear theme" button. At least it would be nice to have an option to enforce such a behaviour.

**Comment by brunowalraven** [comment]
+1 

It would be ideal if the clear theme option was optional. 
Is the repo still being maintained? If so, I can make the changes and create a PR for it.

Thanks

**Comment by tonai** [comment]
Not a fan of having the clear functionnality as a fact you have a default theme (you might have situation where you want a default clearable theme).
So I added a `clearable` parameter.
Here is the PR: https://github.com/tonai/storybook-addon-themes/issues/26

**Comment by tonai** [comment]
Version 5.5.0 just published.
Enjoy :smiley:
