### ISSUE TITLE
Add support for theming Docs?

### ISSUE THREAD

**Issue by ZachJW34** [tonai/storybook-addon-themes#27]
This add-on only supports `viewMode === story`. Can this add-on be extended to work with `addon/docs`?
![image](https://user-images.githubusercontent.com/25158820/79877061-67ac0c00-83b1-11ea-838c-6db5fd89ea59.png)

**Comment by ghost** [comment]
@ZachJW34  Same here. I have a few components which are dependent on the theme class. It will be really a cool feature to have when we have controls also present on the Docs.

@tonai  please let us know. Thanks 😊.

**Comment by chrisheinzelmann** [comment]
That would be a really useful feature. 
@jpzwarte created a Pull Request for that: #29 
I tested it and it works fine.

@tonai can you accept it?

**Comment by tonai** [comment]
Hi all,
sorry I was very busy lately.
I just merged the PR.
I will check tomorrow if I can create a new version.

**Comment by tonai** [comment]
Version 5.5.0 just published.
Enjoy :smiley:

**Comment by akhileshThapliyal** [comment]
Hi @crohrer,

Great addition 👍 . However, I think the theme selected under the docs tab does not propagate to the preview section of the docs. For Instance, today the docs loads in an iframe which has the theme applied correctly, in addition to this the content loaded within the preview section is also an iframe and I see that the theme does not apply to this iframe's body.

Is it possible to extend the theme under docs to the preview section's body tag as well?

Regards,
Akhilesh
