### ISSUE TITLE
Expose channel key/arguments for setting the theme when loading the story in an iFrame

### ISSUE THREAD

**Issue by sknep** [tonai/storybook-addon-themes#30]
I'd like to be able to set the theme from an outside frame by using postMessage() on the preview's iFrame, but I can't decipher the channel key and arguments required for this addon. Something like the following:

```js
window.postMessage(
  JSON.stringify({ 
    key: 'storybook-channel', 
    event: { type: 'storybook-addon-themes/change', args: [{ selected: 'theme-name'}] } }),
  "*"
);
```
Does this addon use the storybook channel? I don't see any channel-related logging in the console when interacting with the theme selector as I do when switching knobs and other addon options.

**Comment by tonai** [comment]
Hi @sknep , sorry for my late reply, I was really busy lately.
Yes this addon use the storybook channel to communicate between the interface and the preview iframe but only when you chose to use the decorator: https://github.com/tonai/storybook-addon-themes#usage-with-decorator.
When you change the theme with the selector it emits an event with the key `storybook-addon-themes/change` with the selected themeName information.
You can see it there: https://github.com/tonai/storybook-addon-themes/blob/master/src/manager/ThemeSelector.tsx#L115

**Comment by tonai** [comment]
I have created a PR for the `storybook-addon-themes/change` to be dispatched even if no decorator is set: https://github.com/tonai/storybook-addon-themes/pull/32

**Comment by sknep** [comment]
Thanks!

**Comment by tonai** [comment]
Version 5.5.0 just published.
Enjoy :smiley:
