### ISSUE TITLE
Warnings of peer dependencies

### ISSUE THREAD

**Issue by afonsomatos** [tonai/storybook-addon-themes#38]
Usually you just use one, either react, svelte or vue.
But if so, you'll get some annoying warnings:

```
warning " > storybook-addon-themes@6.0.0" has unmet peer dependency "svelte@*".
warning " > storybook-addon-themes@6.0.0" has unmet peer dependency "vue@*".
```

Can you remove it from peerDependencies? No need to be there.

**Comment by tonai** [comment]
Fixed in 6.0.1 release
