### ISSUE TITLE
Add targetElement option

### ISSUE THREAD

**Issue by Yankovsky** [tonai/storybook-addon-themes#5]
Currently theme classes are added to body. But [storyshots addon](https://github.com/storybookjs/storybook/tree/master/addons/storyshots) only makes snapshot of story itself. I want resulting snapshots to include theme or maybe even to test one component with different themes.
I suggest adding targetElement option which can be either dom element or dom element id. I can do it myself just want your opinion on the issue.

Some screenshots to explain the problem:

Dom:
![http://s.csssr.ru/U02D248T6/2019-06-11-1535-ud3e28khlr.png](http://s.csssr.ru/U02D248T6/2019-06-11-1535-ud3e28khlr.png)

Snapshot:
![http://s.csssr.ru/U02D248T6/2019-06-11-1608-8l67xdz7xb.png](http://s.csssr.ru/U02D248T6/2019-06-11-1608-8l67xdz7xb.png)

**Comment by tonai** [comment]
Hi @Yankovsky,
ok I understand your need with this scenario.
Adding a `targetElement` option can be a solution, or maybe we can wrap the story inside a decorator that will be responsible for the theme classes.
In this case we can have a simpler option `useDecorator`.
Do you think this solution can work in your scenario ?

**Comment by Yankovsky** [comment]
So we can wrap themes addon in useDecorator? I am not familiar with storybook api.

**Comment by tonai** [comment]
Decorators are used to wrap your story : https://storybook.js.org/docs/addons/introduction/
I think they should be compatible with the storyshots addon.
It needs some testing but I think this approach is more clean.
And in fact it also should be the default implementation.
I will try to dig into this issue this weekend and I will let you know so you can confirm it works in your case.

**Comment by tonai** [comment]
Hi @Yankovsky ,
I have pushed the new `feat/decorator` branch.

To use the decorator globally add it in the `.storybook\config.js` file:
```js
import { addDecorator, addParameters} from '@storybook/react';
import { withThemes } from 'storybook-addon-themes';

addParameters({
  themes: [
    { name: 'twitter', class: ['theme-twt', 'light-mode'], color: '#00aced', default: true },
    { name: 'facebook', class: ['theme-fb', 'dark-mode'], color: '#3b5998' },
  ],
});
addDecorator(withThemes);
```


Or to use the decorator locally add it inyour stories file:
```js
import { withThemes } from 'storybook-addon-themes';

const stories = storiesOf('Button', module);
stories.addParameters({
  themes: [
    { name: 'twitter', class: ['theme-twt', 'light-mode'], color: '#00aced' },
    { name: 'facebook', class: ['theme-fb', 'dark-mode'], color: '#3b5998' },
  ],
});
stories.addDecorator(withThemes);
```

The class should not be added to the body but it will use a wrapping `div`.
Can you try if this work in your case ?

**Comment by Yankovsky** [comment]
@tonai I'll try it this evening. So now instead of adding a class to body on change in ThemeSelector (or on initialization), addon will add the class to decorator element and it will be rendered for every story, is it correct?
Doesn't it conflict with previous approach?

**Comment by tonai** [comment]
It should not.
If you don't use the decorator it will fall back to the previous implementation and use the body.

**Comment by Yankovsky** [comment]
Interesting approach, sounds good.

**Comment by Yankovsky** [comment]
It works but I've got errors during snapshot testing
![http://s.csssr.ru/U02D248T6/2019-06-19-13-37-17-ku7zv_.jpg](http://s.csssr.ru/U02D248T6/2019-06-19-13-37-17-ku7zv_.jpg)

Seems like react hooks don't support shallow render. I've tried to update dependencies but it didn't work.

**Comment by tonai** [comment]
When you talk about shallow rendering, is it done with enzyme ?

Another question:
How have you imported this addon in your project ?

**Comment by Yankovsky** [comment]
I use [@storybook/addon-storyshots](
https://github.com/storybookjs/storybook/tree/master/addons/storyshots/storyshots-core) which depends on [enzyme-to-json](https://github.com/adriantoine/enzyme-to-json) package. It uses slightly outdated versions of react/react-dom/react-test-renderer and enzyme.
I'll try to fork these repos and update dependencies.

**Comment by Yankovsky** [comment]
> How have you imported this addon in your project ?

.storybook/addons.js:
```
import 'storybook-addon-themes/register';
```

**Comment by Yankovsky** [comment]
Ok, seems like this line is not needed anymore. Still I get the same error even without it.

**Comment by Yankovsky** [comment]
Line `import 'storybook-addon-themes/register';` is still needed because without it there will be no ThemeSelector at Storybook's top panel.

**Comment by Yankovsky** [comment]
I experience some very strange bugs and I think that the reason they are happening is dependency resolution in npm/yarn.

**Comment by Yankovsky** [comment]
Other reason could be that some modules have postinstall scripts affected by babel/eslint/stylelint configs in my project.

**Comment by Yankovsky** [comment]
Seems like everything is fine with your changes it is storybook's bug.
I've opened an issue in their repo https://github.com/storybookjs/storybook/issues/7152

**Comment by tonai** [comment]
Thanks for yout feedback.
In fact I've experienced the same issue one time and it was because I was using npm link (or a symlink) to use a UI project as a dependency of another project.
In this scenario and due to the node_modules resolution, it was using two different versions of React (I've got one react in project/node_modules/react and another one in project/node_modules/uiProject/node_modules/react).
Importing the UI project with npm using the git repo URL solved my issue.

**Comment by Yankovsky** [comment]
@tonai you are welcome and thanks for great work.

Reinstalling modules or using different package manager (npm/yarn) solved issues I've described above but it is not reliable.

Can you answer the question here https://github.com/tonai/storybook-addon-themes/commit/434eb0e6eca8e2c11b92d80d82a6fc619610e01d#r34008033

**Comment by tonai** [comment]
Hello @Yankovsky,
I have published some updates.
If it's ok with you, I will publish a new version.

**Comment by Yankovsky** [comment]
@tonai looks good!
