### ISSUE TITLE
Multiple tailwind configs

### ISSUE THREAD

**Issue by cromosom** [tonai/storybook-addon-themes#53]
We are working on a monorepo with multiple next.js apps each with their own tailwind.config.js. I was wondering if I could setup a central storybook which is able to switch those configs.

Do you think this is possible with this plugin?

**Comment by tonai** [comment]
Hello @cromosom , I'm not really familiar with tailwind, does it generate final CSS files for each of your apps ?

**Comment by cromosom** [comment]
Hey @tonai,
yes, its processing everything via postCSS and generates a css file in the end

**Comment by jowan** [comment]
I'm very interested in this too. I am developing a master and multiple sub-themes for Drupal, and would like to swap one main css/scss file via the plugin. I'm not quite sure how to create a custom decorator to facilitate this.

**Comment by tonai** [comment]
Then maybe you can create a decorator that will inject the builded CSS ?
Like this example: https://github.com/tonai/storybook-addon-themes#html-example

**Comment by cromosom** [comment]
> Then maybe you can create a decorator that will inject the builded CSS ?
> Like this example: https://github.com/tonai/storybook-addon-themes#html-example

this worked! thx

**Comment by pierce-h** [comment]
@cromosom were you able to figure out how to target multiple tailwind  CSS builds using the method suggested above? Thanks!

**Comment by cromosom** [comment]
> @cromosom were you able to figure out how to target multiple tailwind CSS builds using the method suggested above? Thanks!

actually it was the React example which worked for me

**Comment by grantralls** [comment]
This plugin only supports storybook 6.0.x and the support section in the storybook discord isn't responding (over 48 hours). Is there a recommended method to achieve this functionality with updated storybook versions or is there a goal to see this plugin updated to a newer storybook version?
