### ISSUE TITLE
Suggestion to add this addon to storybook addons gallery

### ISSUE THREAD

**Issue by Yankovsky** [tonai/storybook-addon-themes#6]
https://github.com/storybookjs/storybook/issues/7052

**Comment by Yankovsky** [comment]
https://github.com/storybookjs/storybook/pull/7465

**Comment by tonai** [comment]
Thanks a lot for your efforts @Yankovsky 

I still can't see it on the page https://storybook.js.org/addons/
Maybe it's not delivered yet.
We may close this issue when it is done.

**Comment by tonai** [comment]
I have created anoter pull request https://github.com/storybookjs/frontpage/pull/90 tu update the https://storybook.js.org/addons/ page.
