### ISSUE TITLE
Import predefined theme from library to be used

### ISSUE THREAD

**Issue by yoshiafk** [tonai/storybook-addon-themes#61]
Hey, is there a way that I can just import predefined theme variable into the list ?
Something like
```
import {Dark, Light, Dim} from 'edu-style'

 themes :{
    default: "light",
    list: [Dark, Light, Dim
    ]
  },
```

**Comment by tonai** [comment]
Hello @yoshiafk ,
yes if all the variables you put in the list correspond to a theme object. (objects that looks like that: `{ name: 'twitter', class: 'theme-twt', color: '#00aced' }`)
