### ISSUE TITLE
Set first theme as default unless default flag is set for some theme

### ISSUE THREAD

**Issue by Yankovsky** [tonai/storybook-addon-themes#7]
Currently no theme selected as default if default is false or undefined for all themes.

**Comment by Yankovsky** [comment]
I can make a pr.

**Comment by tonai** [comment]
Hello,
I don't think this is a feature I would like because you also might want to have no theme for default.

**Comment by Yankovsky** [comment]
I haven't thought about that. I'll close the issue.
