### ISSUE TITLE
Support of Vue

### ISSUE THREAD

**Issue by padevone** [tonai/storybook-addon-themes#9]
Hi. I have trouble like this: https://github.com/storybookjs/storybook/issues/4770.
Will you add support for VueJS? If you need i can create reproduced repo.

**Comment by tonai** [comment]
Hi @padevone,
thanks for reporting.
I will have a look.

**Comment by tonai** [comment]
In my tests it fails when you try to use the decorator version.

But it is ok when you don't use the decorator: https://github.com/tonai/storybook-addon-themes#usage-without-the-decorator (only use `addParameters`).

Tell me if it is ok for you with that update and I will update the doc (and also I won't deprecate it).

Maybe I will add the decorator version for vue later when I have some time (The decorator means one version for each framework).

**Comment by padevone** [comment]
Hi, @tonai. Thanks for reply. I will try this way without decorator.
